site_name: Materiały — Informatyka
theme:
  name: material
  language: pl
nav:
  - Podstawy Programowania:
      - Klasa 3: podstawy-programowania/klasa-3/index.md
      - Klasa 4: podstawy-programowania/klasa-4/index.md
      - Powtórka: podstawy-programowania/powtorka/index.md
  - ASO:
      - Klasa 2: aso/klasa-2/index.md
      - Klasa 3: aso/klasa-3/index.md
