site_name: Materiały — Informatyka
site_url: https://a-wieczorek-nauczyciel.github.io/informatyka-zawodowe/
theme:
  name: material
  language: pl
  palette:
    - scheme: default
      toggle:
        icon: material/weather-night
        name: Przełącz na tryb ciemny
    - scheme: slate
      toggle:
        icon: material/weather-sunny
        name: Przełącz na tryb jasny
  features:
    - navigation.tabs
    - navigation.indexes
    - navigation.top
    - content.code.copy
    - toc.integrate
nav:
  - Start: index.md
  - Podstawy Programowania:
      - podstawy-programowania/index.md
      - Klasa 3: podstawy-programowania/klasa-3/index.md
      - Klasa 4: podstawy-programowania/klasa-4/index.md
      - Powtórka: podstawy-programowania/powtorka/index.md
  - ASO:
      - aso/index.md
      - Klasa 2: aso/klasa-2/index.md
      - Klasa 3: aso/klasa-3/index.md
